### PR TITLE
do not take in account offset when window ask to be maximized

### PR DESCRIPTION
**Pull request by frstrikerman**
I just merged the change to my config and I made something that isn't quite a mistake but the fullscreen take in account the offset and I think it shouldn't

### CODE REVIEW

**Comment by venam** [comment]
So I've tested the changes. I think it's a good direction however I'm not sure it's the right behavior for firefox for example. Maybe we should only set the fullscreen atom when receiving the client message that says so instead of setting it when we want the window to take all the screen estate. Or maybe we could set it only when doing the override border fullscreen instead.

What do you think?

**Comment by venam** [comment]
Also, as an NB in the `unmaxwin` function there's no need for that ewmh->_NET_WM_STATE_FULLSCREEN because the size of the atom list is 0, this could simply be NULL.

**Comment by venam** [comment]
something such as 
```
	if (!with_offsets) {
		xcb_change_property(conn, XCB_PROP_MODE_REPLACE, client->id,
			ewmh->_NET_WM_STATE, XCB_ATOM_ATOM, 32, 1, &ewmh->_NET_WM_STATE_FULLSCREEN);
	}
```
in the maxwin should do the trick, plus the changes of your commit.

**Comment by frstrikerman** [comment]
I think that it might be a good idea to consider a window set as fullscreen only if it's without offsets

**Comment by frstrikerman** [comment]
I'm in favor of two function instead of everything in `maxwin`. if we do so user will have to change their configuration but I think having a function called `fullscreen` and another called `maximize` based on the same base is a far better option

**Comment by venam** [comment]
> a function called `fullscreen` and another called `maximize`

So fullscreen would be the one ignoring the offsets and maximize the one taking them into consideration if I understood properly. Or is it that fullscreen would be the one with the atom and the maximize the one without. It's a bit confusing.

It's not a bad idea, though I have a preference for keeping the current scenario and not break the current users' configuration files.

**Comment by frstrikerman** [comment]
> It's not a bad idea, though I have a preference for keeping the current scenario and not break the current users' configuration files.
I agree on that but I think it will be less confusing naming wise
>So fullscreen would be the one ignoring the offsets and maximize the one taking them into consideration if I understood properly. Or is it that fullscreen would be the one with the atom and the maximize the one without. It's a bit confusing.
the first option

**Comment by venam** [comment]
> I agree on that but I think it will be less confusing naming wise

Alright, let's go with that option. Be sure to update the default configuration file to so that changes are propagated everywhere.

That will be adding a one line function "fullscreen". and removing some enum from the definition so that the config goes from:

```C
    // Full screen window without borders
    {  MOD ,              XK_x,         maximize,          {.i=TWOBWM_FULLSCREEN}},
    //Full screen window without borders overiding offsets
    {  MOD |SHIFT ,       XK_x,          maximize,          {.i=TWOBWM_FULLSCREEN_OVERRIDE_OFFSETS}},
```

to becoming:

```C
    // Full screen window without borders
    {  MOD ,              XK_x,         maximize,          {}},
    //Full screen window without borders overiding offsets
    {  MOD |SHIFT ,       XK_x,          fullscreen,          {}},
```

So in the end it might actually clean the code.

**Comment by frstrikerman** [comment]
Yeah I already know that I had to check this part of the code on my last pull request I just don't understand where the value of the `enum` (is it the position in the enumeration) is set and why are they unamed. I never really used enum in c

**Comment by frstrikerman** [comment]
Yeah I knew I had to made those change I already checked this part of the code

**Comment by frstrikerman** [comment]
It might be a good idea to merge this first commit because I think it's a little bit awkward that fullscreen isn't a real fullscreen for now (I personally use the master branch because 0.2 doesn't integrate certain fix like mpv and urxvt one). and also I won't be as active as those 2 weeks because it's the end of my holydays

**Pull request merged**
