### PR TITLE
_NET_WM_STATE_FULLSCREEN support

### PR DESCRIPTION
**Pull request by frstrikerman**
For now it just add the proper ATOM to maximized window

### CODE REVIEW

**Comment by venam** [comment]
I'm not sure this will do the trick, the atom will still be there when the window is un-maximized.

**Comment by frstrikerman** [comment]
It wasn't finished yet but when I unmzximized window xprop gave me a `_NET_WM_STATE(ATOM) = `

**Comment by frstrikerman** [comment]
I first tried to delete the property but I saw that awesome gave me the same result

**Comment by frstrikerman** [comment]
And I want to had the possibility for a window to ask for this atom  and get fullscreen that way we can get fullscreen html video in one step

**Comment by venam** [comment]
Alright, I haven't tested it yet I didn't know the behavior was inherent to X11.  
I'll give it a try then.

**Comment by frstrikerman** [comment]
And I get a strange result when I create a new both in this branch and your master with xprop
```{bash}$ xprop _NET_WM_STATE
_NET_WM_STATE(_NET_WM_STATE) = 0x1, 0x0```

**Comment by frstrikerman** [comment]
on a new terminal on open box I got this results:
```
$ # just after creation
$ xprop _NET_WM_STATE                                                       
_NET_WM_STATE(ATOM) = 
$ # In fullscreen
$ xprop _NET_WM_STATE                                                                                                                                                                                                                     
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
$ # back to normal
$ xprop _NET_WM_STATE                                                       
_NET_WM_STATE(ATOM) = 
```

**Comment by venam** [comment]
The 0x01 and 0x00 are part of the `newwin` function:

```
	long data[] = {
		XCB_ICCCM_WM_STATE_NORMAL,
		XCB_NONE
	};
...
	xcb_change_property(conn, XCB_PROP_MODE_REPLACE, client->id,
			ewmh->_NET_WM_STATE, ewmh->_NET_WM_STATE, 32, 2, data);
```
This should probably be updated to an ewmh state instead, a remnant from an older change.

As for the events for the state I guess this can be added as a method handling `XCB_EVENT_MASK_PROPERTY_CHANGE` or exposure events.

**Comment by venam** [comment]
So this can be done in the clientmessage handler, listening to XCB_CLIENT_MESSAGE events.

As per the specs: https://standards.freedesktop.org/wm-spec/wm-spec-latest.html

The `e->type` should be `ewmh->_NET_ACTIVE_WINDOW`, the `e->format` 32, and the data filled as followed:  

```
  window  = the respective client window
  message_type = _NET_WM_STATE
  format = 32
  data.l[0] = the action, as listed below
  data.l[1] = first property to alter
  data.l[2] = second property to alter
  data.l[3] = source indication
  other data.l[] elements = 0
```

We're interested in that union data type: `e->data.data32[1]` or `e->data.data32[2]` if it's equal to an `ewmh->_NET_WM_STATE_FULLSCREEN`, if it is then we can get the current window `e->window` and see the type of action `e->data.data32[0]` if it's either one of the following and act accordingly:

```
typedef enum {
  /* Remove/unset property */
  XCB_EWMH_WM_STATE_REMOVE = 0,
  /* Add/set property */
  XCB_EWMH_WM_STATE_ADD = 1,
  /* Toggle property  */
  XCB_EWMH_WM_STATE_TOGGLE = 2
} xcb_ewmh_wm_state_action_t;
```

This should quickstart a series of changes to support more ewmh/icccm.

**Comment by frstrikerman** [comment]
In the `clientmessage` function you use an or 
```
	if ((e->type == ATOM[wm_change_state] && e->format==32
			&& e->data.data32[0]==XCB_ICCCM_WM_STATE_ICONIC)
			|| e->type == ewmh->_NET_ACTIVE_WINDOW) {
```
and ater you test if the client is iconic or not wouldn't be better to check this inside another if ?

**Comment by frstrikerman** [comment]
In the documentation they say that the `e->type` should be `_NET_WM_STATE` and not `ewmh->_NET_ACTIVE_WINDOW`
>  To change the state of a mapped window, a Client MUST send a _NET_WM_STATE client message to the root window:
```
  window  = the respective client window
  message_type = _NET_WM_STATE
  format = 32
  data.l[0] = the action, as listed below
  data.l[1] = first property to alter
  data.l[2] = second property to alter
  data.l[3] = source indication
  other data.l[] elements = 0
```

**Comment by venam** [comment]
> and ater you test if the client is iconic or not wouldn't be better to check this inside another if ?

Yes it would be better, especially if we were to add more ewmh handling in there.

> In the documentation they say that the `e->type` should be `_NET_WM_STATE` and not `ewmh->_NET_ACTIVE_WINDOW`

Also you're right, this is a bug.

**Comment by frstrikerman** [comment]
Full screen does work with the last commit I checked with MPV Firefox and chromium

**Comment by frstrikerman** [comment]
oh and I was'nt pointing a bug when I talked about the documentation I wanted to point out that in your previous comment you said to check if the `e->type` was `ewmh->_NET_ACTIVE_WINDOW` but in this case you have to check if it's `_NET_WM_STATE`

**Comment by frstrikerman** [comment]
I'm wondering if we shouldn't modify ewmh support related stuff in another pull request

**Comment by frstrikerman** [comment]
> Everything related to fullscreen can be put together in this commit.
you mean one pull request ?
> I checked it, it looks good. Maybe it would be good to squash all those commits together and fix the indentation too.
or create a big commit with all the modification. 
for indentation issue I have seen one on github but the indention isn't messed up in vim

**Comment by venam** [comment]
> you mean one pull request ?

Yes, sure.

>  for indentation issue I have seen one on github but the indention isn't messed up in vim

Use the same styling [KNF](https://man.openbsd.org/style).

**Comment by frstrikerman** [comment]
it might be a good idea to mention the KNF style inside the README.Md and other code convention

**Comment by venam** [comment]
> it might be a good idea to mention the KNF style inside the README.Md and other code convention  
> and maybe add a vi modeline would be useful too

Excellent ideas, those sure would put the ambiguities aside.

Thanks for all the help, those changes needed to be made for some time but I just didn't find the time to work on them.

**Comment by frstrikerman** [comment]
how do I squash the commit together ? I create a new pull request and apply the diff with `patch` ?

**Comment by venam** [comment]
> how do I squash the commit together ? I create a new pull request and apply the diff with `patch` ?

It's a git command. You do a [git squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git#5201642) and then git push with force so that it overrides your previous commits here.

**Comment by frstrikerman** [comment]
there was another indentation error I just fixed it

**Comment by venam** [comment]
Alright, this is good, I'll merge it.

**Comment by frstrikerman** [comment]
I just merged the change to my config and I made something that isn't quite a mistake but the fullscreen take in account the offset and I think it shouldn't

**Pull request merged**
