### PR TITLE
fixwindow_without_cloning

### PR DESCRIPTION
**Pull request by netcrop**
1, fixwindow(client) add/remove the client window to/from all workspaces except the current one. If I understand correct, only one workspace is visible to user from a certain monitor in a certain time. 

2, If the previous statement is corrent, The fixwindow(client) can be as easy as setting client->fix to true/false. and changeworkspace_helper(ws)  needs send the fixed client to the desired worksapce.

3, I made as few changes as possible to archive the same result as the original code. In case this pull is accepted, more clean up maybe needed. E.g: if xcb_change_property still required in fixwindow(client)?

### CODE REVIEW

**Comment by venam** [comment]
Indeed, you are correct on all points.
Your way saves a bit of memory by not storing the fixed window in all the workspace but keeps it on a single one at a time.  
Also, in all cases the fixed window doesn't need to be on all of them as it's never going to be unmapped.

**Comment by netcrop** [comment]
1, Besides a little memory saving, there are some other benefits.  Each client holding a array wsitem[ws] that indicates which workspaces the client belongs to. Since each client only visible on a certain monitor at a certain time, only in one workspace. This array shall became a single client->wsitem instead.  Therefore many loops can be avoided. 

2, If some developer wish fixwindow(client) have a cross monitor behaviour, this array can be changed as client->wsitem[monitorsize] instead.

**Comment by netcrop** [comment]
This pull has been arround a while now. Maybe you haven't got time to synthetic check the code yet? Are you suggesting I do it and come back with a new pull?

**Comment by venam** [comment]
The pull is working fine, as mentioned. It simply needs a little syntactic check: removing the commented lines and using tab to align properly.  
Sorry, I was waiting for those before merging.

**Comment by netcrop** [comment]
Done. Sorry for miss-understanding. Could you pls also feeback about client->wsitem[ws]? Are you prefer using client-wsitem there by eliminate loops instead (maybe a new pull)?

**Comment by venam** [comment]
That's great, I'll merge.  
As for the `client->wsitem[ws]` I guess what you mean is that we now don't need anymore an array pointing to the position in `wslist` because the window/client can only be on a single workspace at a time.  
I agree, we could use `client->wsitem` or `client->wspointer` plus maybe the workspace number inside the client itself. This requires many changes so it's better to have it in another commit to make sure everything is in place properly.

**Comment by netcrop** [comment]
Yes, I think it's worth the trouble to make the changes. Since the program will be little faster and code little cleaner. I'll come up with a new pull later.

**Pull request merged**
