### PR TITLE
Fix for possible memory leak

### PR DESCRIPTION
**Pull request by ltsdw**

### CODE REVIEW

**Comment by venam** [comment]
Hello @ltsdw,
This is a good catch.
Can you please squash the two commits into one and I'll merge.

Thanks a lot!

**Comment by ltsdw** [comment]
@venam Done. and thank you 😄

**Comment by wereket78** [comment]
After entering my password, Firefox freezes, I had to killall firefox every time. Am currently on xfce4 and the firefox password prompt on sites like for example github works. I had last week complete pc freeze where I had to reboot.

**Comment by venam** [comment]
@wereket78 Do you have a particular methodology to reproduce this issue and is this related to this particular pull request?

**Comment by wereket78** [comment]
I am now back on 2bwm, firefox works, I think a firefox update resolved the problem.

**Comment by terebeza** [comment]
Hello
Window titles don't show, like here 
image

my exemple emacs looks like this 
image
Thank you

**Comment by ltsdw** [comment]
Why my PR became a issue tracker? lol 🤣 

Wouldn't it be better if there was a proper place to report bugs/requests/open issues, etc?

**Pull request merged**
